task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]
num_classes: 7

# ==================== Dataset Configuration ====================
train_dataloader: 
  type: DataLoader
  dataset: 
    type: DualModalityCocoDetection
    img_folder_rgb: ./datasets/SeaRGBT-Tiny/images/train/RGB
    img_folder_ir: ./datasets/SeaRGBT-Tiny/images/train/IR
    ann_file: ./datasets/SeaRGBT-Tiny/annotations/train.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Mosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.5, 1.5], probability: 1.0, fill_value: 0, use_cache: False, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
  shuffle: True
  num_workers: 4
  drop_last: True
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset: 
    type: DualModalityCocoDetection
    # img_folder_rgb: ./datasets/SeaRGBT-Tiny/images/test/RGB
    img_folder_rgb: ./datasets/SeaRGBT-Tiny/images/val/RGB
    # img_folder_ir: ./datasets/SeaRGBT-Tiny/images/test/IR
    img_folder_ir: ./datasets/SeaRGBT-Tiny/images/val/IR
    # ann_file: ./datasets/SeaRGBT-Tiny/annotations/test.json
    ann_file: ./datasets/SeaRGBT-Tiny/annotations/val.json
    return_masks: False
    transforms:
      type: Compose
  shuffle: False
  num_workers: 4
  drop_last: False
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction

# ==================== Categories & Core Settings ====================
class_names: ['bus', 'car', 'cyclist', 'drone', 'pedestrian', 'plane', 'ship']

__include__: [
  '../base/deim.yml'
]

output_dir: ./outputs/CMRNet_SeaRGBT-Tiny
model: CMRNet

optimizer:
  type: AdamW
  params:
    - params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0004
    - params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0004
      weight_decay: 0.
    - params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.
  lr: 0.0008
  betas: [0.9, 0.999]
  weight_decay: 0.0001

epoches: 160
flat_epoch: 78    
no_aug_epoch: 12
lr_gamma: 1.0

# ==================== CMRNet Architecture ====================
backbone:
  - [-1, IdentityInput, []]                                           # 0
  - [-1, ModalitySelector, [1]]                                       # 1 (RGB)
  - [-2, ModalitySelector, [2]]                                       # 2 (TIR)

  - [1, StemBlock, [16, 16, True]]                                    # 3 (RGB_Stem)
  - [2, StemBlock, [16, 16, True]]                                    # 4 (TIR_Stem)

  - [3, HG_Stage, [16, 32, 1, 3, False, False, 3, True, 'se']]        # 5 (RGB_P2)
  - [4, HG_Stage, [16, 32, 1, 3, False, False, 3, True, 'se']]        # 6 (TIR_P2)

  - [[5, 6], MCDF, [32]]                                              # 7 (Fused_P2)

  - [5, HG_Stage, [32, 128, 1, 3, True, False, 3, True, 'se']]        # 8 (RGB_P3)
  - [6, HG_Stage, [32, 128, 1, 3, True, False, 3, True, 'se']]        # 9 (TIR_P3)
 
  - [7, SCDown, [32, 3, 2]]                                           # 10 

  - [[8, 9], MCDF, [128]]                                             # 11 
  - [[11, 10], Concat, []]                                            # 12 
  - [-1, ConvNormLayer_fuse, [128, 1, 1]]                             # 13 (Fused_P3)

  - [-1, HG_Stage, [32, 256, 2, 3, True, True, 5, True, 'se']]        # 14 (P4)
  - [-1, HG_Stage, [64, 512, 1, 3, True, True, 5, True, 'se']]        # 15 (P5)

encoder:
  - [7, ConvNormLayer_fuse, [64, 1, 1]]                               # 16 
  - [14, ConvNormLayer_fuse, [128, 1, 1]]                             # 17 
  - [15, ConvNormLayer_fuse, [128, 1, 1]]                             # 18 

  - [-1, TransformerEncoderBlock, [8, 512, 0.1, "relu", 10000, False]]# 19 
  - [-1, ConvNormLayer_fuse, [128, 1, 1]]                             # 20
  - [-1, nn.Upsample, [None, 2, "nearest"]]                           # 21
  - [[-1, 17], Concat, []]                                            # 22 
  - [-1, RepNCSPELAN4, [128, 256, 21, 2, False, 'silu']]              # 23 

  - [-1, ConvNormLayer_fuse, [64, 1, 1]]                              # 24
  - [-1, nn.Upsample, [None, 4, "nearest"]]                           # 25 
  - [[-1, 16], Concat, []]                                            # 26 
  - [-1, RepNCSPELAN4, [64, 128, 21, 2, False, 'silu']]               # 27 

  - [-1, SCDown, [128, 3, 4, 'silu']]                                 # 28 
  - [[-1, 23], Concat, []]                                            # 29 
  - [-1, PolyBlock, [256]]                                            # 30 (PolyBlock on P4)

  - [-1, SCDown, [128, 3, 2, 'silu']]                                 # 31 
  - [[-1, 20], Concat, []]                                            # 32 
  - [-1, PolyBlock, [256]]                                            # 33 (PolyBlock on P5)

decoder:
  - [[30, 33], DGQS_Transformer, {"feat_strides":[16, 32], "hidden_dim": 128, "num_levels": 2, "num_layers": 3, "num_points": [6, 6], "dim_feedforward": 512, "using_dynamic_query": false, "using_densitymap_iter": 10000}]
